### PR TITLE
Change locale code mo to ro_MD (Closes: elementary/terminal#598)

### PR DESCRIPTION
**Pull request by fmneto**
This should be enough for terminal?

Not sure about the rest of the distro, though.

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
Hey thanks for the PR! You'll also need to update the LINGUAS file, otherwise bots will automatically regenerate the other file

**Comment by fmneto** [comment]
On 2021-06-15 10:06, Daniel Foré wrote:
> @danrabbit requested changes on this pull request.
>
> Hey thanks for the PR! You'll also need to update the LINGUAS file, otherwise bots will automatically regenerate the other file

	Oops! Let that one escape. I've sent a new commit, things should be
OK now.

	Cheers!

--
Francisco

**Review by danrabbit — APPROVED** [review]
Right on, thanks for fixing this!

**Comment by fmneto** [comment]
Glad to help :)

**Pull request merged**
