### PR TITLE
Use Solarized Dark for dark UI

### PR DESCRIPTION
**Pull request by cassidyjames**
As an alternative to #390 if we wanted Terminal to be more explicitly Solarized Dark, like the Code syntax highlighting. Going for something like this:

image (7)

For some reason loading the stylesheet isn't working yet.

### CODE REVIEW

**Comment by fabiozaramella** [comment]
I don't know...in my opinion the neutral dark style of your previous branch is better for the eyes, and not only it is coherent with dark style across the OS but it also better matches Terminal's icon.
This one looks too blue-greenish.

**Comment by cassidyjames** [comment]
@fabiozaramella we use Solarized Dark in Code for syntax highlighting, and we were chatting about aligning the developer tools to use solarized for their dark styles. The neutral dark is a good default for the stylesheet since it affect content-creation and editing apps like Photos and video editors, but that's less of a big deal with developer tools.

I imagine we'd also update the Terminal icon to match, like we did with the Code icon and Solarized Light.

**Comment by fabiozaramella** [comment]
@cassidyjames Well, if Solarized (both light and dark) is going to be the default style for developer tools I'm perfectly ok with this.  

My only concern is coherence across different apps. For example, this will require to update not only Terminal icon but also dark UI for Code (at the moment only the text view uses the solarized dark color scheme) and... if Terminal and Code then get a Solarized dark UI their light counterparts, with default grey decorations, will look odd, wouldn't they?

**Comment by cassidyjames** [comment]
@fabiozaramella It’s _almost_ like this is a draft PR to experiment with things! 😜️ Yes, there are a lot of implications and we’ll need to decide what the scope is. I’m just pushing this up here in a draft PR instead of keeping it to myself on my machine.

**Comment by danrabbit** [comment]
This way too blue, I don't like it

**Comment by cassidyjames** [comment]
Closing as it was an experiment but I don't see it getting merged

**Pull request closed without merging**
