### PR TITLE
Fix #98 - Pass F keys to TerminalWidget first.

### LINKED ISSUE #98: F-keys not work in mc
F-keys not work,  I have to mouse-click on "10 Quit" to quit from Midnight Commander

### PR DESCRIPTION
**Pull request by jeremypw**
See issue #98.

This fix was tested with htop but should also work with other commandline programs.

### CODE REVIEW

**Comment by jeremypw** [comment]
Added medium priority label as it is associated with broken functionality under some circumstances.

**Comment by donadigo** [comment]
I believe we shouldn't do things like this. This could lead to some unwanted behaviour. In theory returning `false` should pass the event further to the terminal widget itself.

**Comment by jeremypw** [comment]
Seeking a more elegant solution. 

Just putting 
> return current_terminal.key_event (e);

at the end of the keyhandler blocks effect of F11 and may cause other regressions.

**Comment by jeremypw** [comment]
Withdrawing since better solution submitted by donadigo.

**Comment by jeremypw** [comment]
PR closed in favour of fix-F10-key

**Pull request closed without merging**
