### PR TITLE
TerminalWidget: Port Context Menu to GLib.MenuModel and Gtk.PopoverMenu

### PR DESCRIPTION
**Pull request by Marukesu**
In preparation to Gtk4. The changing from Gtk.Menu to Gtk.PopoverMenu happens because Gtk.Menu will inherit the monospace font from the TerminalWidget, sadly, it requires that we lost the accels in the menu for now.

### CODE REVIEW

**Comment by jeremypw** [comment]
How near are we to switching to Gtk4? Would it be better to leave this until switch is imminent so degradation of UI is minimised?

**Comment by Marukesu** [comment]
> How near are we to switching to Gtk4?

We don't have the Gtk4 version of VTE in jammy, so it would need to wait for once we are "done" with releases for OS 7.

> Would it be better to leave this until switch is imminent so degradation of UI is minimised?

I'm fine in waiting for it, this part of code won't have much changes, if any, until there.

**Comment by jeremypw** [comment]
Adding blocked label - waiting for Gtk4 version of Vte.

**Comment by jeremypw** [comment]
Looks like the context menu is broken in master at the moment, so it might be better to proceed with this.  Might be possible work around the accelerator issue. I'll look into it.

**Comment by danirabbit** [comment]
Closing since #769 was merged

**Pull request closed without merging**
