### PR TITLE
-n option to open a new window instead of a new tab

### LINKED ISSUE #440: Super+T dosen't open new Terminal anymore
Hello,

Since the update this morning, my shortcut to open a new terminal doesn't work anymore : the first I open works but once I have 1 teminal openned it doesn't open more terminal.

Regards,
Gregoire

### PR DESCRIPTION
**Pull request by robn**
Fixes #440 

[Reopening #446, which I closed by mistake]

Adds `-n` option to force a new window to open.

### CODE REVIEW

**Comment by robn** [comment]
From #446:

> The get_last_window () function's name no longer reflects its actual action - it does not always return the last window, even if there is one. As it is a private function I think it would be safe enough to rename it and maybe pass the option as a parameter in case the function needs to be used to get the last window anyway. You could then create the new window in this function and return it instead of the callers having to test the result and then create a new window.

I started looking into this and it looks like there's a lot wrong with how windows are selected/created in response to options. I'll stick a pin in the PR and send some cleanups and through that sort all this out before coming back to this one.

**Comment by jeremypw** [comment]
@robn  Please do not let the scope of the PR increase unnecessarily as it will delay approval and merging.

**Comment by robn** [comment]
Alright, then I won't bother refactoring at all, and will just make sure restored tabs are handled properly. The rest I'll save for other PRs.

**Comment by robn** [comment]
Ok, that's the simplest implementation of `-n` I know how to do. Have at it!

**Pull request merged**
