### PR TITLE
Use Granite.SwitchModelButton

### PR DESCRIPTION
**Pull request by pongloongyeat**
As title implies. There's some other deprecations that I'd like to check out but perhaps in a separate PR.

### CODE REVIEW

**Comment by pongloongyeat** [comment]
Could anyone comment on whether or not the builds were supposed to pass before commit 4b544124609d3c156f09d9d6ac1643bd447afc86 (Granite version bump)? I'm using `Granite.SwitchModelButton` which should require minimum 6.0.0 but the build still passed on `Granite` 5.5.0.

**Review by danrabbit — CHANGES_REQUESTED** [review]
Works as expected. Nice to simplify all this!

Can you bump the required version in the README as well? :)

**Comment by pongloongyeat** [comment]
@danrabbit it's done!

**Review by danrabbit — APPROVED** [review]
Great! Thanks again

**Pull request merged**
