### PR TITLE
Add 5 new themes and 3 text palette 

### PR DESCRIPTION
**Pull request by redian23**
# Last update 
## Preview

Screenshot from 2019-10-15 17-32-10
Screenshot from 2019-10-15 17-32-15

# Preview themes
#### High Contrast
High Contrast
#### White
White
### Solized dark
Solized dark
### Solized black
Pink
### Pink
Silver
### Monokai Dark
Monokai Dark
### Dracula
Dracula

### CODE REVIEW

**Comment by stsdc** [comment]
The idea of theming is good. I think that Terminal should have the ability to apply user defined styles. But fresh, after install Terminal is OK with 3 initial themes.

**Comment by redian23** [comment]
"But fresh, after install Terminal is OK with 3 initial themes."
What do you mean??

**Comment by stsdc** [comment]
@redian23 I just think that Terminal doesn't need more themes.

**Comment by ryonakano** [comment]
> I just think that Terminal doesn't need more themes. But needs mechanism that allows to add custom themes e.g. using dotfiles

We've already had a ticket for that, see #418.

**Pull request closed without merging**
