### PR TITLE
MainWindow: Apply font changes on the fly

### PR DESCRIPTION
**Pull request by Exalm**
Fixes https://github.com/elementary/terminal/issues/283

### CODE REVIEW

**Comment by Exalm** [comment]
While the MR fixes it if you don't change hidden settings, it still won't work if you select a custom font. Though unlike Code, Terminal doesn't implement zooming via that preference. So, I wonder if this font should be special-cased to be applied even if a custom font is used.

**Comment by jeremypw** [comment]
@danrabbit Do we need to have a separate font setting for Terminal, especially as it is not exposed in the UI?

**Comment by Exalm** [comment]
Rebased, also moved system gsettings creation into `Application` to match the existing ones.

**Comment by Exalm** [comment]
Oh wait, actually pushed the correct one now.

**Comment by danrabbit** [comment]
@jeremypw I'm not sure I 100% understand the question, but the system monospace font is also used in Code, for example, so I don't think a Terminal-specific setting makes sense necessarily

**Comment by Exalm** [comment]
Wel, Code has a setting. And it's even exposed in the UI and is also used for zooming. Terminal has a setting too, but it's only in gsettings.

**Comment by jeremypw** [comment]
@danrabbit OK, so the setting `io.elementary.terminal.settings.font` could be removed and the system monospace font always used?

**Comment by Exalm** [comment]
Added a line to appdata changelog.

**Pull request merged**
