### PR TITLE
MainWindow: Use the Gtk.EventControllerKey controller to handle the key events

### PR DESCRIPTION
**Pull request by tintou**
This makes the copy function work again.
Fix GtkMenu warnings on the go.

### CODE REVIEW

**Comment by jeremypw** [comment]
Hm, Gtk.EventControllerKey could be useful in other projects (e.g. Files) as well I think :thinking:

**Comment by tintou** [comment]
@jeremypw yes, it is the future way to handle events and has been backported to GTK3 so that the transition to GTK4 can be prepared ( https://developer.gnome.org/gtk4/unstable/gtk-migrating-3-to-4.html#id-1.7.4.3.14 )

**Review by jeremypw — CHANGES_REQUESTED** [review]
This seems to break natural copy - `<Ctrl>C` results in `^C` appearing in the terminal.  Not immediately obvious why as you have implemented similar code.

**Comment by jeremypw** [comment]
AFAICT, the key press event is not actually reaching the EventControllerKey.key_pressed controller :disappointed:

**Comment by tintou** [comment]
It indeed only work if the widget has focus which isn't the case here, closing in favor of another solution.

**Pull request closed without merging**
