### PR TITLE
Add moving current tab shortcuts

### PR DESCRIPTION
**Pull request by Mohelm97**
Adds #322

### CODE REVIEW

**Comment by Mohelm97** [comment]
I think it would be better to add it over the DynamicNotebook, But quite not sure, Like why they added the shortcut for travelling between tabs here rather than the DynamicNotebook?

**Comment by jeremypw** [comment]
On reflection, I think there are problems implementing actions within Granite itself so the PR's approach is probably OK.

**Comment by jeremypw** [comment]
@Mohelm97 Would you like to fix the conflict so that this PR can be progressed, thanks :-)

**Comment by Mohelm97** [comment]
@jeremypw Cool, I will do it soon :D

**Comment by Mohelm97** [comment]
@jeremypw It's ready now :D

**Pull request closed without merging**
